define([], function() {
  return {
    "PropertyPaneDescription": "Merge list columns",
    "BasicGroupName": "Styling",
    "VisibilityGroupName": "Visibility status",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "WhoCanSee": "Who can see this web part (detailsList result)?",
    "WhoCanEdit": "Who can edit this web part?",
    "Everyone": "Everyone",
    "Admins":"Only administrators",
    "MergeLists":"Merge Lists",
    "OpenInTeams": "Open in Teams",
    "ListOptionsFieldLabel": "Visibility",
    "VisibilityOptionUsers": "Show the merge lists solution to all users",
    "VisibilityOptionAdministrators": "Show the merge lists solution to administrators only",
    "VisibilityOptionHide": "Hide the merge lists solution from users and administrators",
    "VisibilitySaving": "Saving...",
    "VisibilitySaved": "Saved",

    "SelectSite":"Site selection",
    "SelectList": "List selection",
    "SelectColumn" : "Column selection",
    "ListFor":"Lists blong to:",
    "ColumnFor": "Columns belong to:",
    "ShowListData": "Show grid",
    
    // Merge
    "MergeSettings": "Solution settings",
    "CloseButtonText": "Close",
    "ButtonText": "Button Text",
    "ButtonIconName": "Icon Name",
    "ButtonAlignment": "Button alignment",
    "ButtonAlignmentLeft": "Left",
    "ButtonAlignmentCenter": "Center",
    "ButtonAlignmentRight": "Right",
    "ButtonSize": "Button Size",
    "ButtonShowAs": "Show as",
    "ButtonShowAsButton": "Button",
    "ButtonShowAsLink": "Link",

    //LoadGrid
    "FilterLabel": "Filter :",
    "FilterTextboxPlaceholder": "Filter term",
    "SelectColumn": "Select a column",
  }
});